
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 24 11:21:11 COT 2016
//----------------------------------------------------

package ejemplocup;

import java_cup.runtime.*;
import java.io.FileReader;
import java.util.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Jan 24 11:21:11 COT 2016
  */
public class AnalizadorSintactico extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalizadorSintactico() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\136\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\002\003\000\002\002\002\000\002\012\004" +
    "\000\002\012\003\000\002\012\004\000\002\012\003\000" +
    "\002\012\004\000\002\012\003\000\002\012\004\000\002" +
    "\012\003\000\002\013\004\000\002\013\003\000\002\022" +
    "\005\000\002\023\006\000\002\023\006\000\002\023\005" +
    "\000\002\023\005\000\002\025\005\000\002\025\004\000" +
    "\002\027\007\000\002\027\006\000\002\027\007\000\002" +
    "\027\006\000\002\024\004\000\002\024\003\000\002\024" +
    "\004\000\002\024\003\000\002\026\005\000\002\026\004" +
    "\000\002\030\004\000\002\030\003\000\002\030\003\000" +
    "\002\030\004\000\002\030\003\000\002\031\004\000\002" +
    "\031\003\000\002\031\004\000\002\031\003\000\002\031" +
    "\004\000\002\031\003\000\002\031\004\000\002\031\003" +
    "\000\002\034\012\000\002\035\016\000\002\032\012\000" +
    "\002\033\012\000\002\047\005\000\002\047\005\000\002" +
    "\047\005\000\002\047\005\000\002\036\003\000\002\040" +
    "\005\000\002\040\005\000\002\040\005\000\002\040\005" +
    "\000\002\040\005\000\002\040\005\000\002\040\005\000" +
    "\002\040\005\000\002\041\005\000\002\042\002\000\002" +
    "\042\005\000\002\042\005\000\002\044\005\000\002\044" +
    "\005\000\002\044\005\000\002\044\005\000\002\044\005" +
    "\000\002\044\005\000\002\044\005\000\002\044\005\000" +
    "\002\045\005\000\002\046\002\000\002\046\005\000\002" +
    "\046\005\000\002\014\010\000\002\017\013\000\002\015" +
    "\006\000\002\021\011\000\002\016\003\000\002\016\003" +
    "\000\002\020\003\000\002\020\003\000\002\020\003\000" +
    "\002\037\003\000\002\037\003\000\002\043\003\000\002" +
    "\050\003\000\002\050\003\000\002\050\003\000\002\050" +
    "\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\253\000\016\002\ufffd\012\005\013\023\016\022\017" +
    "\006\020\013\001\002\000\004\002\255\001\002\000\004" +
    "\021\uffaf\001\002\000\004\021\uffac\001\002\000\016\002" +
    "\ufff5\012\ufff5\013\ufff5\016\ufff5\017\ufff5\020\ufff5\001\002" +
    "\000\016\002\uffff\012\005\013\023\016\022\017\006\020" +
    "\013\001\002\000\016\002\ufff7\012\ufff7\013\ufff7\016\ufff7" +
    "\017\ufff7\020\ufff7\001\002\000\004\021\242\001\002\000" +
    "\004\021\uffab\001\002\000\004\021\232\001\002\000\016" +
    "\002\ufff3\012\ufff3\013\ufff3\016\ufff3\017\ufff3\020\ufff3\001" +
    "\002\000\016\002\ufffe\012\005\013\023\016\022\017\006" +
    "\020\013\001\002\000\014\012\005\013\023\016\022\017" +
    "\006\020\013\001\002\000\016\002\ufff9\012\ufff9\013\ufff9" +
    "\016\ufff9\017\ufff9\020\ufff9\001\002\000\016\002\ufffb\012" +
    "\ufffb\013\ufffb\016\ufffb\017\ufffb\020\ufffb\001\002\000\004" +
    "\021\uffad\001\002\000\004\021\uffae\001\002\000\016\012" +
    "\005\013\023\016\022\017\006\020\013\031\041\001\002" +
    "\000\004\021\036\001\002\000\004\021\031\001\002\000" +
    "\016\012\uffe4\013\uffe4\016\uffe4\017\uffe4\020\uffe4\031\uffe4" +
    "\001\002\000\016\012\uffe6\013\uffe6\016\uffe6\017\uffe6\020" +
    "\uffe6\031\uffe6\001\002\000\004\051\032\001\002\000\004" +
    "\022\033\001\002\000\004\025\034\001\002\000\004\004" +
    "\035\001\002\000\020\002\uffb3\012\uffb3\013\uffb3\016\uffb3" +
    "\017\uffb3\020\uffb3\031\uffb3\001\002\000\004\051\037\001" +
    "\002\000\004\004\040\001\002\000\020\002\uffb1\012\uffb1" +
    "\013\uffb1\016\uffb1\017\uffb1\020\uffb1\031\uffb1\001\002\000" +
    "\022\010\063\030\045\032\051\035\055\036\047\046\046" +
    "\050\050\051\064\001\002\000\016\012\uffe5\013\uffe5\016" +
    "\uffe5\017\uffe5\020\uffe5\031\uffe5\001\002\000\016\012\uffe7" +
    "\013\uffe7\016\uffe7\017\uffe7\020\uffe7\031\uffe7\001\002\000" +
    "\016\002\ufff2\012\ufff2\013\ufff2\016\ufff2\017\ufff2\020\ufff2" +
    "\001\002\000\016\002\uffe2\012\uffe2\013\uffe2\016\uffe2\017" +
    "\uffe2\020\uffe2\001\002\000\016\005\076\006\075\037\101" +
    "\040\100\041\074\042\102\001\002\000\004\010\164\001" +
    "\002\000\016\005\076\006\075\037\101\040\100\041\074" +
    "\042\102\001\002\000\004\010\147\001\002\000\014\010" +
    "\uffdd\030\uffdd\046\uffdd\050\uffdd\051\uffdd\001\002\000\006" +
    "\005\076\006\075\001\002\000\026\010\uffcc\011\uffcc\030" +
    "\uffcc\037\uffcc\040\uffcc\041\uffcc\042\uffcc\046\uffcc\050\uffcc" +
    "\051\uffcc\001\002\000\004\031\133\001\002\000\022\010" +
    "\uffd5\030\uffd5\032\uffd5\035\uffd5\036\uffd5\046\uffd5\050\uffd5" +
    "\051\uffd5\001\002\000\024\010\uffe0\030\uffe0\037\101\040" +
    "\100\041\074\042\102\046\uffe0\050\uffe0\051\uffe0\001\002" +
    "\000\014\010\063\030\117\046\046\050\050\051\064\001" +
    "\002\000\022\010\uffd9\030\uffd9\032\uffd9\035\uffd9\036\uffd9" +
    "\046\uffd9\050\uffd9\051\uffd9\001\002\000\022\010\uffdb\030" +
    "\uffdb\032\uffdb\035\uffdb\036\uffdb\046\uffdb\050\uffdb\051\uffdb" +
    "\001\002\000\010\011\uffc2\046\106\050\105\001\002\000" +
    "\016\005\076\006\075\037\101\040\100\041\074\042\102" +
    "\001\002\000\022\010\uffdf\030\uffdf\032\051\035\055\036" +
    "\047\046\uffdf\050\uffdf\051\uffdf\001\002\000\022\010\uffd7" +
    "\030\uffd7\032\uffd7\035\uffd7\036\uffd7\046\uffd7\050\uffd7\051" +
    "\uffd7\001\002\000\022\010\uffd8\030\uffd8\032\uffd8\035\uffd8" +
    "\036\uffd8\046\uffd8\050\uffd8\051\uffd8\001\002\000\022\010" +
    "\uffda\030\uffda\032\uffda\035\uffda\036\uffda\046\uffda\050\uffda" +
    "\051\uffda\001\002\000\022\010\uffd6\030\uffd6\032\uffd6\035" +
    "\uffd6\036\uffd6\046\uffd6\050\uffd6\051\uffd6\001\002\000\022" +
    "\010\uffdc\030\uffdc\032\uffdc\035\uffdc\036\uffdc\046\uffdc\050" +
    "\uffdc\051\uffdc\001\002\000\004\051\104\001\002\000\012" +
    "\010\uffa5\046\uffa5\050\uffa5\051\uffa5\001\002\000\012\010" +
    "\uffa9\046\uffa9\050\uffa9\051\uffa9\001\002\000\012\010\uffaa" +
    "\046\uffaa\050\uffaa\051\uffaa\001\002\000\004\051\103\001" +
    "\002\000\012\010\uffa6\046\uffa6\050\uffa6\051\uffa6\001\002" +
    "\000\012\010\uffa7\046\uffa7\050\uffa7\051\uffa7\001\002\000" +
    "\012\010\uffa4\046\uffa4\050\uffa4\051\uffa4\001\002\000\026" +
    "\010\uffcb\011\uffcb\030\uffcb\037\uffcb\040\uffcb\041\uffcb\042" +
    "\uffcb\046\uffcb\050\uffcb\051\uffcb\001\002\000\016\010\uffd0" +
    "\011\uffd0\030\uffd0\046\uffd0\050\uffd0\051\uffd0\001\002\000" +
    "\006\005\076\006\075\001\002\000\006\005\076\006\075" +
    "\001\002\000\004\011\110\001\002\000\032\005\uffc3\006" +
    "\uffc3\010\uffc3\011\uffc3\030\uffc3\037\uffc3\040\uffc3\041\uffc3" +
    "\042\uffc3\046\uffc3\050\uffc3\051\uffc3\001\002\000\004\046" +
    "\112\001\002\000\004\011\uffc0\001\002\000\004\050\114" +
    "\001\002\000\004\011\uffc1\001\002\000\014\010\uffde\030" +
    "\uffde\046\uffde\050\uffde\051\uffde\001\002\000\024\010\uffe1" +
    "\030\uffe1\037\101\040\100\041\074\042\102\046\uffe1\050" +
    "\uffe1\051\uffe1\001\002\000\016\002\uffe3\012\uffe3\013\uffe3" +
    "\016\uffe3\017\uffe3\020\uffe3\001\002\000\012\010\063\046" +
    "\124\050\121\051\123\001\002\000\006\005\076\006\075" +
    "\001\002\000\016\010\uffcd\011\uffcd\030\uffcd\046\uffcd\050" +
    "\uffcd\051\uffcd\001\002\000\006\005\076\006\075\001\002" +
    "\000\006\005\076\006\075\001\002\000\006\010\063\046" +
    "\127\001\002\000\026\010\uffc7\011\uffc7\030\uffc7\037\uffc7" +
    "\040\uffc7\041\uffc7\042\uffc7\046\uffc7\050\uffc7\051\uffc7\001" +
    "\002\000\026\010\uffc9\011\uffc9\030\uffc9\037\uffc9\040\uffc9" +
    "\041\uffc9\042\uffc9\046\uffc9\050\uffc9\051\uffc9\001\002\000" +
    "\006\010\063\050\131\001\002\000\026\010\uffca\011\uffca" +
    "\030\uffca\037\uffca\040\uffca\041\uffca\042\uffca\046\uffca\050" +
    "\uffca\051\uffca\001\002\000\026\010\uffc5\011\uffc5\030\uffc5" +
    "\037\uffc5\040\uffc5\041\uffc5\042\uffc5\046\uffc5\050\uffc5\051" +
    "\uffc5\001\002\000\012\010\063\046\124\050\121\051\123" +
    "\001\002\000\004\030\135\001\002\000\004\036\136\001" +
    "\002\000\004\010\137\001\002\000\012\010\063\046\046" +
    "\050\050\051\064\001\002\000\012\037\101\040\100\041" +
    "\074\042\102\001\002\000\004\011\142\001\002\000\022" +
    "\010\uffd1\030\uffd1\032\uffd1\035\uffd1\036\uffd1\046\uffd1\050" +
    "\uffd1\051\uffd1\001\002\000\010\010\063\046\146\050\144" +
    "\001\002\000\026\010\uffc4\011\uffc4\030\uffc4\037\uffc4\040" +
    "\uffc4\041\uffc4\042\uffc4\046\uffc4\050\uffc4\051\uffc4\001\002" +
    "\000\026\010\uffc8\011\uffc8\030\uffc8\037\uffc8\040\uffc8\041" +
    "\uffc8\042\uffc8\046\uffc8\050\uffc8\051\uffc8\001\002\000\026" +
    "\010\uffc6\011\uffc6\030\uffc6\037\uffc6\040\uffc6\041\uffc6\042" +
    "\uffc6\046\uffc6\050\uffc6\051\uffc6\001\002\000\012\010\063" +
    "\046\046\050\050\051\064\001\002\000\004\011\151\001" +
    "\002\000\004\033\152\001\002\000\004\031\153\001\002" +
    "\000\012\010\063\046\124\050\121\051\123\001\002\000" +
    "\004\030\155\001\002\000\024\010\uffd4\030\uffd4\032\uffd4" +
    "\034\156\035\uffd4\036\uffd4\046\uffd4\050\uffd4\051\uffd4\001" +
    "\002\000\004\031\157\001\002\000\012\010\063\046\124" +
    "\050\121\051\123\001\002\000\004\030\161\001\002\000" +
    "\022\010\uffd3\030\uffd3\032\uffd3\035\uffd3\036\uffd3\046\uffd3" +
    "\050\uffd3\051\uffd3\001\002\000\004\050\163\001\002\000" +
    "\016\010\uffcf\011\uffcf\030\uffcf\046\uffcf\050\uffcf\051\uffcf" +
    "\001\002\000\012\010\063\046\046\050\050\051\064\001" +
    "\002\000\004\011\166\001\002\000\004\035\167\001\002" +
    "\000\004\031\170\001\002\000\012\010\063\046\124\050" +
    "\121\051\123\001\002\000\004\030\172\001\002\000\022" +
    "\010\uffd2\030\uffd2\032\uffd2\035\uffd2\036\uffd2\046\uffd2\050" +
    "\uffd2\051\uffd2\001\002\000\004\046\174\001\002\000\016" +
    "\010\uffce\011\uffce\030\uffce\046\uffce\050\uffce\051\uffce\001" +
    "\002\000\004\021\227\001\002\000\004\021\200\001\002" +
    "\000\016\002\ufff4\012\ufff4\013\ufff4\016\ufff4\017\ufff4\020" +
    "\ufff4\001\002\000\004\051\201\001\002\000\016\010\203" +
    "\012\uffef\013\uffef\016\uffef\017\uffef\020\uffef\001\002\000" +
    "\014\012\ufff1\013\ufff1\016\ufff1\017\ufff1\020\ufff1\001\002" +
    "\000\016\011\207\012\005\013\023\016\022\017\006\020" +
    "\013\001\002\000\004\021\224\001\002\000\004\021\221" +
    "\001\002\000\016\011\210\012\005\013\023\016\022\017" +
    "\006\020\013\001\002\000\014\012\uffec\013\uffec\016\uffec" +
    "\017\uffec\020\uffec\001\002\000\014\012\uffed\013\uffed\016" +
    "\uffed\017\uffed\020\uffed\001\002\000\004\021\216\001\002" +
    "\000\004\021\213\001\002\000\004\051\214\001\002\000" +
    "\004\024\215\001\002\000\016\011\uffeb\012\uffeb\013\uffeb" +
    "\016\uffeb\017\uffeb\020\uffeb\001\002\000\004\051\217\001" +
    "\002\000\004\024\220\001\002\000\016\011\uffe9\012\uffe9" +
    "\013\uffe9\016\uffe9\017\uffe9\020\uffe9\001\002\000\004\051" +
    "\222\001\002\000\004\024\223\001\002\000\016\011\uffe8" +
    "\012\uffe8\013\uffe8\016\uffe8\017\uffe8\020\uffe8\001\002\000" +
    "\004\051\225\001\002\000\004\024\226\001\002\000\016" +
    "\011\uffea\012\uffea\013\uffea\016\uffea\017\uffea\020\uffea\001" +
    "\002\000\004\051\230\001\002\000\016\010\203\012\uffee" +
    "\013\uffee\016\uffee\017\uffee\020\uffee\001\002\000\014\012" +
    "\ufff0\013\ufff0\016\ufff0\017\ufff0\020\ufff0\001\002\000\004" +
    "\051\233\001\002\000\022\010\203\012\uffef\013\uffef\016" +
    "\uffef\017\uffef\020\uffef\022\033\027\234\001\002\000\004" +
    "\046\235\001\002\000\004\026\236\001\002\000\004\022" +
    "\237\001\002\000\004\025\240\001\002\000\004\004\241" +
    "\001\002\000\016\002\uffb2\012\uffb2\013\uffb2\016\uffb2\017" +
    "\uffb2\020\uffb2\001\002\000\004\051\243\001\002\000\022" +
    "\004\040\010\203\012\uffee\013\uffee\016\uffee\017\uffee\020" +
    "\uffee\027\244\001\002\000\004\046\245\001\002\000\004" +
    "\026\246\001\002\000\004\004\247\001\002\000\016\002" +
    "\uffb0\012\uffb0\013\uffb0\016\uffb0\017\uffb0\020\uffb0\001\002" +
    "\000\016\002\ufff6\012\ufff6\013\ufff6\016\ufff6\017\ufff6\020" +
    "\ufff6\001\002\000\016\002\ufff8\012\ufff8\013\ufff8\016\ufff8" +
    "\017\ufff8\020\ufff8\001\002\000\016\002\000\012\005\013" +
    "\023\016\022\017\006\020\013\001\002\000\016\002\ufffa" +
    "\012\ufffa\013\ufffa\016\ufffa\017\ufffa\020\ufffa\001\002\000" +
    "\016\002\ufffc\012\ufffc\013\ufffc\016\ufffc\017\ufffc\020\ufffc" +
    "\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\253\000\030\002\003\012\007\013\015\014\020\015" +
    "\017\016\013\017\010\020\011\021\006\022\014\023\016" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\024\013\251\014\253\015\252" +
    "\016\013\017\250\020\011\021\247\022\014\023\016\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\016\175\020" +
    "\174\022\176\023\016\001\001\000\014\014\027\015\026" +
    "\016\025\020\024\024\023\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\014" +
    "\014\042\015\041\016\025\020\024\026\043\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\026\030\057\031" +
    "\064\032\065\033\055\034\061\035\060\036\056\040\053" +
    "\041\052\047\051\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\037\124" +
    "\050\172\001\001\000\002\001\001\000\006\037\127\050" +
    "\161\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\037\142\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\050\117\001\001\000\012\036\115" +
    "\040\053\041\052\047\114\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\042\106\001\001\000\006\037\076" +
    "\050\072\001\001\000\012\032\066\033\070\034\071\035" +
    "\067\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\037\112\001\001\000\004\037\110\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\050\117\001\001\000\002\001\001\000\010\036\121" +
    "\040\053\041\052\001\001\000\004\037\127\001\001\000" +
    "\002\001\001\000\004\037\076\001\001\000\004\037\124" +
    "\001\001\000\004\041\125\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\041\131\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\036\133\040\053\041\052\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\036\137\040\053\041\052\047\140\001\001\000" +
    "\004\050\117\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\041\144\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\036\137\040\053\041\052" +
    "\047\147\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\036\153\040\053\041\052\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\036\157\040\053\041\052\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\036\137\040\053\041\052\047\164\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\036" +
    "\170\040\053\041\052\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\025\201\001\001\000\002\001\001\000\010\016" +
    "\204\020\203\027\205\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\016\210\020\211\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\025\230\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\025\201\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\025\230" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\016\175\020\174\022\176\023\016\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    
    /* Reporte de error encontrado. */
    public void report_error(String message, Object info) {
        StringBuilder m = new StringBuilder("Error");
        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
            if (s.left >= 0) {                
                m.append(" in line "+(s.left+1));
                if (s.right >= 0)
                    m.append(", column "+(s.right+1));
            }
        }
        m.append(" : "+message);
        System.err.println(m);
    }
	
   
    /* Cuando se encuentra un error de donde el sistema no puede
        recuperarse, se lanza un error fatal. Se despliega el mensaje
        de error y se finaliza la ejecucion. */
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }

    /* Metodo main para garantizar la ejecucion del analizador
       lexico y sintactico, ademas que se pase como parametro la tabla
       de simbolos correspondiente. */
	   
    public static void main(String[] args){
        try {
            AnalizadorSintactico asin = new AnalizadorSintactico(
                    new AnalizadorLexico( new FileReader(args[0])));
					//System.out.println( "-------------->>>>>>>>>>>>>>>>>>>>>>>"+args[0]);
					
            Object result = asin.parse().value;
            System.out.println("\n*** Resultados finales ***");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSintactico$actions {


   /*Aqui podemos cargar dcodigo asociado a las distintas producciones
 gramaticales, se puede poner metodos y atributos
   */
   
  private final AnalizadorSintactico parser;

  /** Constructor */
  CUP$AnalizadorSintactico$actions(AnalizadorSintactico parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintactico$do_action(
    int                        CUP$AnalizadorSintactico$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintactico$parser,
    java.util.Stack            CUP$AnalizadorSintactico$stack,
    int                        CUP$AnalizadorSintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSintactico$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // oprdrsComparacion ::= DIFERENT 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("oprdrsComparacion",38, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // oprdrsComparacion ::= IGUAL_IGUAL 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("oprdrsComparacion",38, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // oprdrsComparacion ::= MENOR_IGUAL 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("oprdrsComparacion",38, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // oprdrsComparacion ::= MAY_IGUAL 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("oprdrsComparacion",38, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // OperadorMD ::= OP_MULT 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("OperadorMD",33, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // OperadorSR ::= OP_RESTA 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("OperadorSR",29, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // OperadorSR ::= OP_SUMA 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("OperadorSR",29, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // tipovariableCAD ::= STRING 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("tipovariableCAD",14, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // tipovariableCAD ::= BOOL 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("tipovariableCAD",14, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // tipovariableCAD ::= CHAR 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("tipovariableCAD",14, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // tipovariableNUM ::= FLOAT 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("tipovariableNUM",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // tipovariableNUM ::= INT 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("tipovariableNUM",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // vGlobalVectorCAD ::= tipovariableCAD DOSPUNTOS IDENTIFICADOR corchIZQ INTEGERP corchDER SEMI 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("vGlobalVectorCAD",15, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-6)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // variableGlobal2 ::= tipovariableCAD DOSPUNTOS IDENTIFICADOR SEMI 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("variableGlobal2",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // vGlobalVector ::= tipovariableNUM DOSPUNTOS IDENTIFICADOR corchIZQ INTEGERP corchDER IGUAL CERO SEMI 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("vGlobalVector",13, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-8)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // variableGlobal1 ::= tipovariableNUM DOSPUNTOS IDENTIFICADOR IGUAL CERO SEMI 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("variableGlobal1",10, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // crpOperadoCompMD ::= INTEGERP OperadorMD INTEGERP 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("crpOperadoCompMD",36, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // crpOperadoCompMD ::= NUMFLOAT OperadorMD NUMFLOAT 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("crpOperadoCompMD",36, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // crpOperadoCompMD ::= 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("crpOperadoCompMD",36, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // OPcompuestoMD ::= PARENIZQ crpOperadoCompMD PARENDER 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("OPcompuestoMD",35, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // expresionMult ::= OPcompuestoMD OperadorMD NUMFLOAT 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionMult",34, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expresionMult ::= NUMFLOAT OperadorMD OPcompuestoMD 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionMult",34, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expresionMult ::= OPcompuestoMD OperadorMD INTEGERP 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionMult",34, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expresionMult ::= INTEGERP OperadorMD OPcompuestoMD 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionMult",34, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expresionMult ::= OPcompuestoMD OperadorMD OPcompuestoMD 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionMult",34, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expresionMult ::= INTEGERP OperadorMD INTEGERP 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionMult",34, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expresionMult ::= NUMFLOAT OperadorMD NUMFLOAT 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionMult",34, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expresionMult ::= IDENTIFICADOR OperadorMD IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionMult",34, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // crpOperadoComp ::= INTEGERP OperadorSR INTEGERP 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("crpOperadoComp",32, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // crpOperadoComp ::= NUMFLOAT OperadorSR NUMFLOAT 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("crpOperadoComp",32, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // crpOperadoComp ::= 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("crpOperadoComp",32, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // OPcompuesto ::= PARENIZQ crpOperadoComp PARENDER 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("OPcompuesto",31, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expresionSuma ::= OPcompuesto OperadorSR NUMFLOAT 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionSuma",30, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expresionSuma ::= NUMFLOAT OperadorSR OPcompuesto 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionSuma",30, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expresionSuma ::= OPcompuesto OperadorSR INTEGERP 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionSuma",30, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expresionSuma ::= INTEGERP OperadorSR OPcompuesto 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionSuma",30, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expresionSuma ::= OPcompuesto OperadorSR OPcompuesto 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionSuma",30, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expresionSuma ::= INTEGERP OperadorSR INTEGERP 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionSuma",30, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expresionSuma ::= NUMFLOAT OperadorSR NUMFLOAT 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionSuma",30, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expresionSuma ::= IDENTIFICADOR OperadorSR IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionSuma",30, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expreAritmeticas ::= expresionSuma 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expreAritmeticas",28, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expresionesLogicas ::= expreAritmeticas oprdrsComparacion expreAritmeticas 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionesLogicas",37, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresionesLogicas ::= INTEGERP oprdrsComparacion INTEGERP 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionesLogicas",37, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expresionesLogicas ::= NUMFLOAT oprdrsComparacion NUMFLOAT 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionesLogicas",37, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expresionesLogicas ::= IDENTIFICADOR oprdrsComparacion IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresionesLogicas",37, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // do_while ::= DO llaveIZQ expreAritmeticas llaveDER WHILE PARENIZQ expresionesLogicas PARENDER 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("do_while",25, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-7)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // while_do ::= WHILE PARENIZQ expresionesLogicas PARENDER DO llaveIZQ expreAritmeticas llaveDER 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("while_do",24, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-7)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // if_then_else ::= IF PARENIZQ expresionesLogicas PARENDER THEN llaveIZQ expreAritmeticas llaveDER ELSE llaveIZQ expreAritmeticas llaveDER 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("if_then_else",27, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-11)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // if_then ::= IF PARENIZQ expresionesLogicas PARENDER THEN llaveIZQ expreAritmeticas llaveDER 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("if_then",26, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-7)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // controlFlujo ::= do_while 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("controlFlujo",23, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // controlFlujo ::= controlFlujo do_while 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("controlFlujo",23, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // controlFlujo ::= while_do 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("controlFlujo",23, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // controlFlujo ::= controlFlujo while_do 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("controlFlujo",23, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // controlFlujo ::= if_then_else 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("controlFlujo",23, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // controlFlujo ::= controlFlujo if_then_else 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("controlFlujo",23, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // controlFlujo ::= if_then 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("controlFlujo",23, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // controlFlujo ::= controlFlujo if_then 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("controlFlujo",23, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // bloqueComandos ::= expresionesLogicas 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("bloqueComandos",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // bloqueComandos ::= bloqueComandos expresionesLogicas 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("bloqueComandos",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // bloqueComandos ::= controlFlujo 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("bloqueComandos",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // bloqueComandos ::= expreAritmeticas 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("bloqueComandos",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // bloqueComandos ::= bloqueComandos expreAritmeticas 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("bloqueComandos",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // cuerpo ::= llaveIZQ llaveDER 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("cuerpo",20, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // cuerpo ::= llaveIZQ bloqueComandos llaveDER 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("cuerpo",20, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // lstDeclaLocales ::= variableGlobal2 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("lstDeclaLocales",18, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // lstDeclaLocales ::= lstDeclaLocales variableGlobal2 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("lstDeclaLocales",18, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // lstDeclaLocales ::= variableGlobal1 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("lstDeclaLocales",18, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // lstDeclaLocales ::= lstDeclaLocales variableGlobal1 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("lstDeclaLocales",18, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Parametros ::= tipovariableNUM DOSPUNTOS IDENTIFICADOR COMMAA 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("Parametros",21, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Parametros ::= Parametros tipovariableNUM DOSPUNTOS IDENTIFICADOR COMMAA 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("Parametros",21, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Parametros ::= tipovariableCAD DOSPUNTOS IDENTIFICADOR COMMAA 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("Parametros",21, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Parametros ::= Parametros tipovariableCAD DOSPUNTOS IDENTIFICADOR COMMAA 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("Parametros",21, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // lstParametros ::= PARENIZQ PARENDER 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("lstParametros",19, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // lstParametros ::= PARENIZQ Parametros PARENDER 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("lstParametros",19, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // encabezado ::= tipovariableCAD DOSPUNTOS IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("encabezado",17, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // encabezado ::= tipovariableNUM DOSPUNTOS IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("encabezado",17, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // encabezado ::= tipovariableCAD DOSPUNTOS IDENTIFICADOR lstParametros 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("encabezado",17, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // encabezado ::= tipovariableNUM DOSPUNTOS IDENTIFICADOR lstParametros 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("encabezado",17, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // funcion1 ::= encabezado lstDeclaLocales cuerpo 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("funcion1",16, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // conjuntoFunciones ::= funcion1 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("conjuntoFunciones",9, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // conjuntoFunciones ::= conjuntoFunciones funcion1 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("conjuntoFunciones",9, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // declaracionVariablesGlobales ::= vGlobalVectorCAD 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("declaracionVariablesGlobales",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // declaracionVariablesGlobales ::= declaracionVariablesGlobales vGlobalVectorCAD 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("declaracionVariablesGlobales",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // declaracionVariablesGlobales ::= vGlobalVector 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("declaracionVariablesGlobales",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // declaracionVariablesGlobales ::= declaracionVariablesGlobales vGlobalVector 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("declaracionVariablesGlobales",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // declaracionVariablesGlobales ::= variableGlobal2 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("declaracionVariablesGlobales",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // declaracionVariablesGlobales ::= declaracionVariablesGlobales variableGlobal2 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("declaracionVariablesGlobales",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // declaracionVariablesGlobales ::= variableGlobal1 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("declaracionVariablesGlobales",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // declaracionVariablesGlobales ::= declaracionVariablesGlobales variableGlobal1 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("declaracionVariablesGlobales",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // programa ::= 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // programa ::= conjuntoFunciones 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= declaracionVariablesGlobales 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= declaracionVariablesGlobales conjuntoFunciones 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintactico$parser.done_parsing();
          return CUP$AnalizadorSintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

