
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 24 11:21:11 COT 2016
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 15;
  public static final int Entero = 35;
  public static final int DIFERENT = 32;
  public static final int AND_AND = 33;
  public static final int CHAR = 12;
  public static final int PARENIZQ = 6;
  public static final int SEMI = 2;
  public static final int corchDER = 20;
  public static final int INT = 8;
  public static final int FIN = 11;
  public static final int llaveIZQ = 23;
  public static final int IDENTIFICADOR = 39;
  public static final int IGUAL = 16;
  public static final int OR = 34;
  public static final int BOOL = 13;
  public static final int INCREMENTO = 17;
  public static final int IF = 24;
  public static final int IGUAL_IGUAL = 31;
  public static final int MAY_IGUAL = 29;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int OP_MULT = 5;
  public static final int OP_RESTA = 4;
  public static final int PARENDER = 7;
  public static final int llaveDER = 22;
  public static final int ELSE = 26;
  public static final int COMMAA = 18;
  public static final int WHILE = 28;
  public static final int corchIZQ = 21;
  public static final int FLOAT = 9;
  public static final int THEN = 25;
  public static final int NUMFLOAT = 38;
  public static final int STRING = 14;
  public static final int INICIO = 10;
  public static final int OP_SUMA = 3;
  public static final int INTEGERR = 37;
  public static final int MENOR_IGUAL = 30;
  public static final int INTEGERP = 36;
  public static final int CERO = 19;
  public static final int DO = 27;
}

